package com.knight.Bean;

public class accountConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountConfig.loginName
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String loginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountConfig.password
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountConfig.loginType
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String logintype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountConfig.status
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountConfig.loginName
     *
     * @return the value of AccountConfig.loginName
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountConfig.loginName
     *
     * @param loginname the value for AccountConfig.loginName
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountConfig.password
     *
     * @return the value of AccountConfig.password
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountConfig.password
     *
     * @param password the value for AccountConfig.password
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountConfig.loginType
     *
     * @return the value of AccountConfig.loginType
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getLogintype() {
        return logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountConfig.loginType
     *
     * @param logintype the value for AccountConfig.loginType
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setLogintype(String logintype) {
        this.logintype = logintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountConfig.status
     *
     * @return the value of AccountConfig.status
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountConfig.status
     *
     * @param status the value for AccountConfig.status
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }
}