package com.knight.Bean;

import java.util.ArrayList;
import java.util.List;

public class authorityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public authorityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRolenameIsNull() {
            addCriterion("RoleName is null");
            return (Criteria) this;
        }

        public Criteria andRolenameIsNotNull() {
            addCriterion("RoleName is not null");
            return (Criteria) this;
        }

        public Criteria andRolenameEqualTo(String value) {
            addCriterion("RoleName =", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotEqualTo(String value) {
            addCriterion("RoleName <>", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThan(String value) {
            addCriterion("RoleName >", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameGreaterThanOrEqualTo(String value) {
            addCriterion("RoleName >=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThan(String value) {
            addCriterion("RoleName <", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLessThanOrEqualTo(String value) {
            addCriterion("RoleName <=", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameLike(String value) {
            addCriterion("RoleName like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotLike(String value) {
            addCriterion("RoleName not like", value, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameIn(List<String> values) {
            addCriterion("RoleName in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotIn(List<String> values) {
            addCriterion("RoleName not in", values, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameBetween(String value1, String value2) {
            addCriterion("RoleName between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andRolenameNotBetween(String value1, String value2) {
            addCriterion("RoleName not between", value1, value2, "rolename");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNull() {
            addCriterion("RoleID is null");
            return (Criteria) this;
        }

        public Criteria andRoleidIsNotNull() {
            addCriterion("RoleID is not null");
            return (Criteria) this;
        }

        public Criteria andRoleidEqualTo(Long value) {
            addCriterion("RoleID =", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotEqualTo(Long value) {
            addCriterion("RoleID <>", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThan(Long value) {
            addCriterion("RoleID >", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidGreaterThanOrEqualTo(Long value) {
            addCriterion("RoleID >=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThan(Long value) {
            addCriterion("RoleID <", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidLessThanOrEqualTo(Long value) {
            addCriterion("RoleID <=", value, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidIn(List<Long> values) {
            addCriterion("RoleID in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotIn(List<Long> values) {
            addCriterion("RoleID not in", values, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidBetween(Long value1, Long value2) {
            addCriterion("RoleID between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andRoleidNotBetween(Long value1, Long value2) {
            addCriterion("RoleID not between", value1, value2, "roleid");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameIsNull() {
            addCriterion("AuthorityName is null");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameIsNotNull() {
            addCriterion("AuthorityName is not null");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameEqualTo(String value) {
            addCriterion("AuthorityName =", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameNotEqualTo(String value) {
            addCriterion("AuthorityName <>", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameGreaterThan(String value) {
            addCriterion("AuthorityName >", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameGreaterThanOrEqualTo(String value) {
            addCriterion("AuthorityName >=", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameLessThan(String value) {
            addCriterion("AuthorityName <", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameLessThanOrEqualTo(String value) {
            addCriterion("AuthorityName <=", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameLike(String value) {
            addCriterion("AuthorityName like", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameNotLike(String value) {
            addCriterion("AuthorityName not like", value, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameIn(List<String> values) {
            addCriterion("AuthorityName in", values, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameNotIn(List<String> values) {
            addCriterion("AuthorityName not in", values, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameBetween(String value1, String value2) {
            addCriterion("AuthorityName between", value1, value2, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthoritynameNotBetween(String value1, String value2) {
            addCriterion("AuthorityName not between", value1, value2, "authorityname");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoIsNull() {
            addCriterion("AuthorityInfo is null");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoIsNotNull() {
            addCriterion("AuthorityInfo is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoEqualTo(String value) {
            addCriterion("AuthorityInfo =", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoNotEqualTo(String value) {
            addCriterion("AuthorityInfo <>", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoGreaterThan(String value) {
            addCriterion("AuthorityInfo >", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoGreaterThanOrEqualTo(String value) {
            addCriterion("AuthorityInfo >=", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoLessThan(String value) {
            addCriterion("AuthorityInfo <", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoLessThanOrEqualTo(String value) {
            addCriterion("AuthorityInfo <=", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoLike(String value) {
            addCriterion("AuthorityInfo like", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoNotLike(String value) {
            addCriterion("AuthorityInfo not like", value, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoIn(List<String> values) {
            addCriterion("AuthorityInfo in", values, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoNotIn(List<String> values) {
            addCriterion("AuthorityInfo not in", values, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoBetween(String value1, String value2) {
            addCriterion("AuthorityInfo between", value1, value2, "authorityinfo");
            return (Criteria) this;
        }

        public Criteria andAuthorityinfoNotBetween(String value1, String value2) {
            addCriterion("AuthorityInfo not between", value1, value2, "authorityinfo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table authority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}