package com.knight.Bean;

public class authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.RoleName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.RoleID
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.AuthorityName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String authorityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.AuthorityInfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String authorityinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.RoleName
     *
     * @return the value of authority.RoleName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.RoleName
     *
     * @param rolename the value for authority.RoleName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.RoleID
     *
     * @return the value of authority.RoleID
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.RoleID
     *
     * @param roleid the value for authority.RoleID
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.AuthorityName
     *
     * @return the value of authority.AuthorityName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getAuthorityname() {
        return authorityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.AuthorityName
     *
     * @param authorityname the value for authority.AuthorityName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setAuthorityname(String authorityname) {
        this.authorityname = authorityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.AuthorityInfo
     *
     * @return the value of authority.AuthorityInfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getAuthorityinfo() {
        return authorityinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.AuthorityInfo
     *
     * @param authorityinfo the value for authority.AuthorityInfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setAuthorityinfo(String authorityinfo) {
        this.authorityinfo = authorityinfo;
    }
}