package com.knight.Bean;

public class collect {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.userId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.SongSheetName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String songsheetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.Producer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String producer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.userId
     *
     * @return the value of collect.userId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.userId
     *
     * @param userid the value for collect.userId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.SongSheetName
     *
     * @return the value of collect.SongSheetName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSongsheetname() {
        return songsheetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.SongSheetName
     *
     * @param songsheetname the value for collect.SongSheetName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSongsheetname(String songsheetname) {
        this.songsheetname = songsheetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.Producer
     *
     * @return the value of collect.Producer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getProducer() {
        return producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.Producer
     *
     * @param producer the value for collect.Producer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setProducer(String producer) {
        this.producer = producer;
    }
}