package com.knight.Bean;

import java.util.Date;

public class comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long musicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long fabulous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long replycommentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.UserId
     *
     * @return the value of comment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.UserId
     *
     * @param userid the value for comment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.MusicId
     *
     * @return the value of comment.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getMusicid() {
        return musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.MusicId
     *
     * @param musicid the value for comment.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setMusicid(Long musicid) {
        this.musicid = musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.date
     *
     * @return the value of comment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.date
     *
     * @param date the value for comment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Fabulous
     *
     * @return the value of comment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getFabulous() {
        return fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Fabulous
     *
     * @param fabulous the value for comment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setFabulous(Long fabulous) {
        this.fabulous = fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CommentId
     *
     * @return the value of comment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CommentId
     *
     * @param commentid the value for comment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setCommentid(Long commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ReplyCommentId
     *
     * @return the value of comment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getReplycommentid() {
        return replycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ReplyCommentId
     *
     * @param replycommentid the value for comment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setReplycommentid(Long replycommentid) {
        this.replycommentid = replycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}