package com.knight.Bean;

import java.util.Date;

public class ErrorInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ErrorInfo.errorId
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    private Long errorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ErrorInfo.location
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ErrorInfo.creationDate
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ErrorInfo.errorMsg
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    private String errormsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ErrorInfo.errorId
     *
     * @return the value of ErrorInfo.errorId
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public Long getErrorid() {
        return errorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ErrorInfo.errorId
     *
     * @param errorid the value for ErrorInfo.errorId
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public void setErrorid(Long errorid) {
        this.errorid = errorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ErrorInfo.location
     *
     * @return the value of ErrorInfo.location
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ErrorInfo.location
     *
     * @param location the value for ErrorInfo.location
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ErrorInfo.creationDate
     *
     * @return the value of ErrorInfo.creationDate
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ErrorInfo.creationDate
     *
     * @param creationdate the value for ErrorInfo.creationDate
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ErrorInfo.errorMsg
     *
     * @return the value of ErrorInfo.errorMsg
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ErrorInfo.errorMsg
     *
     * @param errormsg the value for ErrorInfo.errorMsg
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg;
    }
}