package com.knight.Bean;

public class fans {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.userid
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.likeuserid
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long likeuserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.userid
     *
     * @return the value of fans.userid
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.userid
     *
     * @param userid the value for fans.userid
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.likeuserid
     *
     * @return the value of fans.likeuserid
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getLikeuserid() {
        return likeuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.likeuserid
     *
     * @param likeuserid the value for fans.likeuserid
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setLikeuserid(Long likeuserid) {
        this.likeuserid = likeuserid;
    }
}