package com.knight.Bean;

public class lrc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lrc.LrcId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long lrcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lrc.LrcName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String lrcname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lrc.Content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lrc.LrcId
     *
     * @return the value of lrc.LrcId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getLrcid() {
        return lrcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lrc.LrcId
     *
     * @param lrcid the value for lrc.LrcId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setLrcid(Long lrcid) {
        this.lrcid = lrcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lrc.LrcName
     *
     * @return the value of lrc.LrcName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getLrcname() {
        return lrcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lrc.LrcName
     *
     * @param lrcname the value for lrc.LrcName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setLrcname(String lrcname) {
        this.lrcname = lrcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lrc.Content
     *
     * @return the value of lrc.Content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lrc.Content
     *
     * @param content the value for lrc.Content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}