package com.knight.Bean;

import java.sql.Timestamp;
import java.util.Date;

public class musicbaseinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long musicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.MusicName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String musicname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.Singer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String singer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.PlayNumber
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long playnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.Time
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.Type
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.Album
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String album;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.Language
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.LyricId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long lyricid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.MusicAddress
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String musicaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.MusicImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String musicimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column musicbaseinfo.CreationDate
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date creationdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.MusicId
     *
     * @return the value of musicbaseinfo.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getMusicid() {
        return musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.MusicId
     *
     * @param musicid the value for musicbaseinfo.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setMusicid(Long musicid) {
        this.musicid = musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.MusicName
     *
     * @return the value of musicbaseinfo.MusicName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getMusicname() {
        return musicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.MusicName
     *
     * @param musicname the value for musicbaseinfo.MusicName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setMusicname(String musicname) {
        this.musicname = musicname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.Singer
     *
     * @return the value of musicbaseinfo.Singer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSinger() {
        return singer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.Singer
     *
     * @param singer the value for musicbaseinfo.Singer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSinger(String singer) {
        this.singer = singer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.PlayNumber
     *
     * @return the value of musicbaseinfo.PlayNumber
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getPlaynumber() {
        return playnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.PlayNumber
     *
     * @param playnumber the value for musicbaseinfo.PlayNumber
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setPlaynumber(Long playnumber) {
        this.playnumber = playnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.Time
     *
     * @return the value of musicbaseinfo.Time
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.Time
     *
     * @param time the value for musicbaseinfo.Time
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.Type
     *
     * @return the value of musicbaseinfo.Type
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.Type
     *
     * @param type the value for musicbaseinfo.Type
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.Album
     *
     * @return the value of musicbaseinfo.Album
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.Album
     *
     * @param album the value for musicbaseinfo.Album
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setAlbum(String album) {
        this.album = album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.Language
     *
     * @return the value of musicbaseinfo.Language
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.Language
     *
     * @param language the value for musicbaseinfo.Language
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.LyricId
     *
     * @return the value of musicbaseinfo.LyricId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getLyricid() {
        return lyricid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.LyricId
     *
     * @param lyricid the value for musicbaseinfo.LyricId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setLyricid(Long lyricid) {
        this.lyricid = lyricid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.MusicAddress
     *
     * @return the value of musicbaseinfo.MusicAddress
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getMusicaddress() {
        return musicaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.MusicAddress
     *
     * @param musicaddress the value for musicbaseinfo.MusicAddress
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setMusicaddress(String musicaddress) {
        this.musicaddress = musicaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.MusicImg
     *
     * @return the value of musicbaseinfo.MusicImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getMusicimg() {
        return musicimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.MusicImg
     *
     * @param musicimg the value for musicbaseinfo.MusicImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setMusicimg(String musicimg) {
        this.musicimg = musicimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column musicbaseinfo.CreationDate
     *
     * @return the value of musicbaseinfo.CreationDate
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column musicbaseinfo.CreationDate
     *
     * @param creationdate the value for musicbaseinfo.CreationDate
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
}