package com.knight.Bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class musicbaseinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public musicbaseinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMusicidIsNull() {
            addCriterion("MusicId is null");
            return (Criteria) this;
        }

        public Criteria andMusicidIsNotNull() {
            addCriterion("MusicId is not null");
            return (Criteria) this;
        }

        public Criteria andMusicidEqualTo(Long value) {
            addCriterion("MusicId =", value, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidNotEqualTo(Long value) {
            addCriterion("MusicId <>", value, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidGreaterThan(Long value) {
            addCriterion("MusicId >", value, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidGreaterThanOrEqualTo(Long value) {
            addCriterion("MusicId >=", value, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidLessThan(Long value) {
            addCriterion("MusicId <", value, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidLessThanOrEqualTo(Long value) {
            addCriterion("MusicId <=", value, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidIn(List<Long> values) {
            addCriterion("MusicId in", values, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidNotIn(List<Long> values) {
            addCriterion("MusicId not in", values, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidBetween(Long value1, Long value2) {
            addCriterion("MusicId between", value1, value2, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicidNotBetween(Long value1, Long value2) {
            addCriterion("MusicId not between", value1, value2, "musicid");
            return (Criteria) this;
        }

        public Criteria andMusicnameIsNull() {
            addCriterion("MusicName is null");
            return (Criteria) this;
        }

        public Criteria andMusicnameIsNotNull() {
            addCriterion("MusicName is not null");
            return (Criteria) this;
        }

        public Criteria andMusicnameEqualTo(String value) {
            addCriterion("MusicName =", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameNotEqualTo(String value) {
            addCriterion("MusicName <>", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameGreaterThan(String value) {
            addCriterion("MusicName >", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameGreaterThanOrEqualTo(String value) {
            addCriterion("MusicName >=", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameLessThan(String value) {
            addCriterion("MusicName <", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameLessThanOrEqualTo(String value) {
            addCriterion("MusicName <=", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameLike(String value) {
            addCriterion("MusicName like", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameNotLike(String value) {
            addCriterion("MusicName not like", value, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameIn(List<String> values) {
            addCriterion("MusicName in", values, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameNotIn(List<String> values) {
            addCriterion("MusicName not in", values, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameBetween(String value1, String value2) {
            addCriterion("MusicName between", value1, value2, "musicname");
            return (Criteria) this;
        }

        public Criteria andMusicnameNotBetween(String value1, String value2) {
            addCriterion("MusicName not between", value1, value2, "musicname");
            return (Criteria) this;
        }

        public Criteria andSingerIsNull() {
            addCriterion("Singer is null");
            return (Criteria) this;
        }

        public Criteria andSingerIsNotNull() {
            addCriterion("Singer is not null");
            return (Criteria) this;
        }

        public Criteria andSingerEqualTo(String value) {
            addCriterion("Singer =", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerNotEqualTo(String value) {
            addCriterion("Singer <>", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerGreaterThan(String value) {
            addCriterion("Singer >", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerGreaterThanOrEqualTo(String value) {
            addCriterion("Singer >=", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerLessThan(String value) {
            addCriterion("Singer <", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerLessThanOrEqualTo(String value) {
            addCriterion("Singer <=", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerLike(String value) {
            addCriterion("Singer like", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerNotLike(String value) {
            addCriterion("Singer not like", value, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerIn(List<String> values) {
            addCriterion("Singer in", values, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerNotIn(List<String> values) {
            addCriterion("Singer not in", values, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerBetween(String value1, String value2) {
            addCriterion("Singer between", value1, value2, "singer");
            return (Criteria) this;
        }

        public Criteria andSingerNotBetween(String value1, String value2) {
            addCriterion("Singer not between", value1, value2, "singer");
            return (Criteria) this;
        }

        public Criteria andPlaynumberIsNull() {
            addCriterion("PlayNumber is null");
            return (Criteria) this;
        }

        public Criteria andPlaynumberIsNotNull() {
            addCriterion("PlayNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPlaynumberEqualTo(Long value) {
            addCriterion("PlayNumber =", value, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberNotEqualTo(Long value) {
            addCriterion("PlayNumber <>", value, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberGreaterThan(Long value) {
            addCriterion("PlayNumber >", value, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberGreaterThanOrEqualTo(Long value) {
            addCriterion("PlayNumber >=", value, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberLessThan(Long value) {
            addCriterion("PlayNumber <", value, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberLessThanOrEqualTo(Long value) {
            addCriterion("PlayNumber <=", value, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberIn(List<Long> values) {
            addCriterion("PlayNumber in", values, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberNotIn(List<Long> values) {
            addCriterion("PlayNumber not in", values, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberBetween(Long value1, Long value2) {
            addCriterion("PlayNumber between", value1, value2, "playnumber");
            return (Criteria) this;
        }

        public Criteria andPlaynumberNotBetween(Long value1, Long value2) {
            addCriterion("PlayNumber not between", value1, value2, "playnumber");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("Time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("Time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("Time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("Time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("Time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("Time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("Time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("Time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("Time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("Time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("Time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("Time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("Time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("Time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("Type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("Type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("Type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("Type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("Type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("Type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("Type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("Type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("Type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("Type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("Type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("Type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("Type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAlbumIsNull() {
            addCriterion("Album is null");
            return (Criteria) this;
        }

        public Criteria andAlbumIsNotNull() {
            addCriterion("Album is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumEqualTo(String value) {
            addCriterion("Album =", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumNotEqualTo(String value) {
            addCriterion("Album <>", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumGreaterThan(String value) {
            addCriterion("Album >", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumGreaterThanOrEqualTo(String value) {
            addCriterion("Album >=", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumLessThan(String value) {
            addCriterion("Album <", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumLessThanOrEqualTo(String value) {
            addCriterion("Album <=", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumLike(String value) {
            addCriterion("Album like", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumNotLike(String value) {
            addCriterion("Album not like", value, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumIn(List<String> values) {
            addCriterion("Album in", values, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumNotIn(List<String> values) {
            addCriterion("Album not in", values, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumBetween(String value1, String value2) {
            addCriterion("Album between", value1, value2, "album");
            return (Criteria) this;
        }

        public Criteria andAlbumNotBetween(String value1, String value2) {
            addCriterion("Album not between", value1, value2, "album");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("Language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("Language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(String value) {
            addCriterion("Language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(String value) {
            addCriterion("Language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(String value) {
            addCriterion("Language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("Language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(String value) {
            addCriterion("Language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(String value) {
            addCriterion("Language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLike(String value) {
            addCriterion("Language like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotLike(String value) {
            addCriterion("Language not like", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<String> values) {
            addCriterion("Language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<String> values) {
            addCriterion("Language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(String value1, String value2) {
            addCriterion("Language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(String value1, String value2) {
            addCriterion("Language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLyricidIsNull() {
            addCriterion("LyricId is null");
            return (Criteria) this;
        }

        public Criteria andLyricidIsNotNull() {
            addCriterion("LyricId is not null");
            return (Criteria) this;
        }

        public Criteria andLyricidEqualTo(Long value) {
            addCriterion("LyricId =", value, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidNotEqualTo(Long value) {
            addCriterion("LyricId <>", value, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidGreaterThan(Long value) {
            addCriterion("LyricId >", value, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidGreaterThanOrEqualTo(Long value) {
            addCriterion("LyricId >=", value, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidLessThan(Long value) {
            addCriterion("LyricId <", value, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidLessThanOrEqualTo(Long value) {
            addCriterion("LyricId <=", value, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidIn(List<Long> values) {
            addCriterion("LyricId in", values, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidNotIn(List<Long> values) {
            addCriterion("LyricId not in", values, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidBetween(Long value1, Long value2) {
            addCriterion("LyricId between", value1, value2, "lyricid");
            return (Criteria) this;
        }

        public Criteria andLyricidNotBetween(Long value1, Long value2) {
            addCriterion("LyricId not between", value1, value2, "lyricid");
            return (Criteria) this;
        }

        public Criteria andMusicaddressIsNull() {
            addCriterion("MusicAddress is null");
            return (Criteria) this;
        }

        public Criteria andMusicaddressIsNotNull() {
            addCriterion("MusicAddress is not null");
            return (Criteria) this;
        }

        public Criteria andMusicaddressEqualTo(String value) {
            addCriterion("MusicAddress =", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressNotEqualTo(String value) {
            addCriterion("MusicAddress <>", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressGreaterThan(String value) {
            addCriterion("MusicAddress >", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressGreaterThanOrEqualTo(String value) {
            addCriterion("MusicAddress >=", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressLessThan(String value) {
            addCriterion("MusicAddress <", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressLessThanOrEqualTo(String value) {
            addCriterion("MusicAddress <=", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressLike(String value) {
            addCriterion("MusicAddress like", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressNotLike(String value) {
            addCriterion("MusicAddress not like", value, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressIn(List<String> values) {
            addCriterion("MusicAddress in", values, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressNotIn(List<String> values) {
            addCriterion("MusicAddress not in", values, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressBetween(String value1, String value2) {
            addCriterion("MusicAddress between", value1, value2, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicaddressNotBetween(String value1, String value2) {
            addCriterion("MusicAddress not between", value1, value2, "musicaddress");
            return (Criteria) this;
        }

        public Criteria andMusicimgIsNull() {
            addCriterion("MusicImg is null");
            return (Criteria) this;
        }

        public Criteria andMusicimgIsNotNull() {
            addCriterion("MusicImg is not null");
            return (Criteria) this;
        }

        public Criteria andMusicimgEqualTo(String value) {
            addCriterion("MusicImg =", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgNotEqualTo(String value) {
            addCriterion("MusicImg <>", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgGreaterThan(String value) {
            addCriterion("MusicImg >", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgGreaterThanOrEqualTo(String value) {
            addCriterion("MusicImg >=", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgLessThan(String value) {
            addCriterion("MusicImg <", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgLessThanOrEqualTo(String value) {
            addCriterion("MusicImg <=", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgLike(String value) {
            addCriterion("MusicImg like", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgNotLike(String value) {
            addCriterion("MusicImg not like", value, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgIn(List<String> values) {
            addCriterion("MusicImg in", values, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgNotIn(List<String> values) {
            addCriterion("MusicImg not in", values, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgBetween(String value1, String value2) {
            addCriterion("MusicImg between", value1, value2, "musicimg");
            return (Criteria) this;
        }

        public Criteria andMusicimgNotBetween(String value1, String value2) {
            addCriterion("MusicImg not between", value1, value2, "musicimg");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNull() {
            addCriterion("CreationDate is null");
            return (Criteria) this;
        }

        public Criteria andCreationdateIsNotNull() {
            addCriterion("CreationDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreationdateEqualTo(Date value) {
            addCriterion("CreationDate =", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotEqualTo(Date value) {
            addCriterion("CreationDate <>", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThan(Date value) {
            addCriterion("CreationDate >", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateGreaterThanOrEqualTo(Date value) {
            addCriterion("CreationDate >=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThan(Date value) {
            addCriterion("CreationDate <", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateLessThanOrEqualTo(Date value) {
            addCriterion("CreationDate <=", value, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateIn(List<Date> values) {
            addCriterion("CreationDate in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotIn(List<Date> values) {
            addCriterion("CreationDate not in", values, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateBetween(Date value1, Date value2) {
            addCriterion("CreationDate between", value1, value2, "creationdate");
            return (Criteria) this;
        }

        public Criteria andCreationdateNotBetween(Date value1, Date value2) {
            addCriterion("CreationDate not between", value1, value2, "creationdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table musicbaseinfo
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table musicbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}