package com.knight.Bean;

public class relationship {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationshipinfo.nativeMusicId
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    private String nativemusicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationshipinfo.externalMusicId
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    private String externalmusicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relationshipinfo.externalType
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    private String externaltype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationshipinfo.nativeMusicId
     *
     * @return the value of relationshipinfo.nativeMusicId
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    public String getNativemusicid() {
        return nativemusicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationshipinfo.nativeMusicId
     *
     * @param nativemusicid the value for relationshipinfo.nativeMusicId
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    public void setNativemusicid(String nativemusicid) {
        this.nativemusicid = nativemusicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationshipinfo.externalMusicId
     *
     * @return the value of relationshipinfo.externalMusicId
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    public String getExternalmusicid() {
        return externalmusicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationshipinfo.externalMusicId
     *
     * @param externalmusicid the value for relationshipinfo.externalMusicId
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    public void setExternalmusicid(String externalmusicid) {
        this.externalmusicid = externalmusicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relationshipinfo.externalType
     *
     * @return the value of relationshipinfo.externalType
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    public String getExternaltype() {
        return externaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relationshipinfo.externalType
     *
     * @param externaltype the value for relationshipinfo.externalType
     *
     * @mbg.generated Fri Jan 03 14:21:48 CST 2020
     */
    public void setExternaltype(String externaltype) {
        this.externaltype = externaltype;
    }
}