package com.knight.Bean;

import java.util.Date;

public class scheduleTaskConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ScheduleTaskConfig.taskName
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String taskname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ScheduleTaskConfig.taskStatus
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String taskstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ScheduleTaskConfig.taskInterval
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String taskinterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ScheduleTaskConfig.lastExecuteTime
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private Date lastexecutetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ScheduleTaskConfig.errorMsg
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    private String errormsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ScheduleTaskConfig.taskName
     *
     * @return the value of ScheduleTaskConfig.taskName
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getTaskname() {
        return taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ScheduleTaskConfig.taskName
     *
     * @param taskname the value for ScheduleTaskConfig.taskName
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setTaskname(String taskname) {
        this.taskname = taskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ScheduleTaskConfig.taskStatus
     *
     * @return the value of ScheduleTaskConfig.taskStatus
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getTaskstatus() {
        return taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ScheduleTaskConfig.taskStatus
     *
     * @param taskstatus the value for ScheduleTaskConfig.taskStatus
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setTaskstatus(String taskstatus) {
        this.taskstatus = taskstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ScheduleTaskConfig.taskInterval
     *
     * @return the value of ScheduleTaskConfig.taskInterval
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getTaskinterval() {
        return taskinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ScheduleTaskConfig.taskInterval
     *
     * @param taskinterval the value for ScheduleTaskConfig.taskInterval
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setTaskinterval(String taskinterval) {
        this.taskinterval = taskinterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ScheduleTaskConfig.lastExecuteTime
     *
     * @return the value of ScheduleTaskConfig.lastExecuteTime
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public Date getLastexecutetime() {
        return lastexecutetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ScheduleTaskConfig.lastExecuteTime
     *
     * @param lastexecutetime the value for ScheduleTaskConfig.lastExecuteTime
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setLastexecutetime(Date lastexecutetime) {
        this.lastexecutetime = lastexecutetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ScheduleTaskConfig.errorMsg
     *
     * @return the value of ScheduleTaskConfig.errorMsg
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ScheduleTaskConfig.errorMsg
     *
     * @param errormsg the value for ScheduleTaskConfig.errorMsg
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg;
    }
}