package com.knight.Bean;

import java.util.Date;

public class sheetcomment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheetcomment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheetcomment.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long sheetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheetcomment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheetcomment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long fabulous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheetcomment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheetcomment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long replycommentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sheetcomment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheetcomment.UserId
     *
     * @return the value of sheetcomment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheetcomment.UserId
     *
     * @param userid the value for sheetcomment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheetcomment.SheetId
     *
     * @return the value of sheetcomment.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getSheetid() {
        return sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheetcomment.SheetId
     *
     * @param sheetid the value for sheetcomment.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSheetid(Long sheetid) {
        this.sheetid = sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheetcomment.date
     *
     * @return the value of sheetcomment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheetcomment.date
     *
     * @param date the value for sheetcomment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheetcomment.Fabulous
     *
     * @return the value of sheetcomment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getFabulous() {
        return fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheetcomment.Fabulous
     *
     * @param fabulous the value for sheetcomment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setFabulous(Long fabulous) {
        this.fabulous = fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheetcomment.CommentId
     *
     * @return the value of sheetcomment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheetcomment.CommentId
     *
     * @param commentid the value for sheetcomment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setCommentid(Long commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheetcomment.ReplyCommentId
     *
     * @return the value of sheetcomment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getReplycommentid() {
        return replycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheetcomment.ReplyCommentId
     *
     * @param replycommentid the value for sheetcomment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setReplycommentid(Long replycommentid) {
        this.replycommentid = replycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sheetcomment.content
     *
     * @return the value of sheetcomment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sheetcomment.content
     *
     * @param content the value for sheetcomment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}