package com.knight.Bean;

import java.util.ArrayList;
import java.util.List;

public class singerbaseinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public singerbaseinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSingeridIsNull() {
            addCriterion("SingerId is null");
            return (Criteria) this;
        }

        public Criteria andSingeridIsNotNull() {
            addCriterion("SingerId is not null");
            return (Criteria) this;
        }

        public Criteria andSingeridEqualTo(Long value) {
            addCriterion("SingerId =", value, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridNotEqualTo(Long value) {
            addCriterion("SingerId <>", value, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridGreaterThan(Long value) {
            addCriterion("SingerId >", value, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridGreaterThanOrEqualTo(Long value) {
            addCriterion("SingerId >=", value, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridLessThan(Long value) {
            addCriterion("SingerId <", value, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridLessThanOrEqualTo(Long value) {
            addCriterion("SingerId <=", value, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridIn(List<Long> values) {
            addCriterion("SingerId in", values, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridNotIn(List<Long> values) {
            addCriterion("SingerId not in", values, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridBetween(Long value1, Long value2) {
            addCriterion("SingerId between", value1, value2, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingeridNotBetween(Long value1, Long value2) {
            addCriterion("SingerId not between", value1, value2, "singerid");
            return (Criteria) this;
        }

        public Criteria andSingernameIsNull() {
            addCriterion("SingerName is null");
            return (Criteria) this;
        }

        public Criteria andSingernameIsNotNull() {
            addCriterion("SingerName is not null");
            return (Criteria) this;
        }

        public Criteria andSingernameEqualTo(String value) {
            addCriterion("SingerName =", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameNotEqualTo(String value) {
            addCriterion("SingerName <>", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameGreaterThan(String value) {
            addCriterion("SingerName >", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameGreaterThanOrEqualTo(String value) {
            addCriterion("SingerName >=", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameLessThan(String value) {
            addCriterion("SingerName <", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameLessThanOrEqualTo(String value) {
            addCriterion("SingerName <=", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameLike(String value) {
            addCriterion("SingerName like", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameNotLike(String value) {
            addCriterion("SingerName not like", value, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameIn(List<String> values) {
            addCriterion("SingerName in", values, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameNotIn(List<String> values) {
            addCriterion("SingerName not in", values, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameBetween(String value1, String value2) {
            addCriterion("SingerName between", value1, value2, "singername");
            return (Criteria) this;
        }

        public Criteria andSingernameNotBetween(String value1, String value2) {
            addCriterion("SingerName not between", value1, value2, "singername");
            return (Criteria) this;
        }

        public Criteria andSingerimgIsNull() {
            addCriterion("SingerImg is null");
            return (Criteria) this;
        }

        public Criteria andSingerimgIsNotNull() {
            addCriterion("SingerImg is not null");
            return (Criteria) this;
        }

        public Criteria andSingerimgEqualTo(String value) {
            addCriterion("SingerImg =", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgNotEqualTo(String value) {
            addCriterion("SingerImg <>", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgGreaterThan(String value) {
            addCriterion("SingerImg >", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgGreaterThanOrEqualTo(String value) {
            addCriterion("SingerImg >=", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgLessThan(String value) {
            addCriterion("SingerImg <", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgLessThanOrEqualTo(String value) {
            addCriterion("SingerImg <=", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgLike(String value) {
            addCriterion("SingerImg like", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgNotLike(String value) {
            addCriterion("SingerImg not like", value, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgIn(List<String> values) {
            addCriterion("SingerImg in", values, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgNotIn(List<String> values) {
            addCriterion("SingerImg not in", values, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgBetween(String value1, String value2) {
            addCriterion("SingerImg between", value1, value2, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingerimgNotBetween(String value1, String value2) {
            addCriterion("SingerImg not between", value1, value2, "singerimg");
            return (Criteria) this;
        }

        public Criteria andSingersexIsNull() {
            addCriterion("SingerSex is null");
            return (Criteria) this;
        }

        public Criteria andSingersexIsNotNull() {
            addCriterion("SingerSex is not null");
            return (Criteria) this;
        }

        public Criteria andSingersexEqualTo(String value) {
            addCriterion("SingerSex =", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexNotEqualTo(String value) {
            addCriterion("SingerSex <>", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexGreaterThan(String value) {
            addCriterion("SingerSex >", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexGreaterThanOrEqualTo(String value) {
            addCriterion("SingerSex >=", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexLessThan(String value) {
            addCriterion("SingerSex <", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexLessThanOrEqualTo(String value) {
            addCriterion("SingerSex <=", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexLike(String value) {
            addCriterion("SingerSex like", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexNotLike(String value) {
            addCriterion("SingerSex not like", value, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexIn(List<String> values) {
            addCriterion("SingerSex in", values, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexNotIn(List<String> values) {
            addCriterion("SingerSex not in", values, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexBetween(String value1, String value2) {
            addCriterion("SingerSex between", value1, value2, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingersexNotBetween(String value1, String value2) {
            addCriterion("SingerSex not between", value1, value2, "singersex");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberIsNull() {
            addCriterion("SingerHotNumber is null");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberIsNotNull() {
            addCriterion("SingerHotNumber is not null");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberEqualTo(Long value) {
            addCriterion("SingerHotNumber =", value, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberNotEqualTo(Long value) {
            addCriterion("SingerHotNumber <>", value, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberGreaterThan(Long value) {
            addCriterion("SingerHotNumber >", value, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberGreaterThanOrEqualTo(Long value) {
            addCriterion("SingerHotNumber >=", value, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberLessThan(Long value) {
            addCriterion("SingerHotNumber <", value, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberLessThanOrEqualTo(Long value) {
            addCriterion("SingerHotNumber <=", value, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberIn(List<Long> values) {
            addCriterion("SingerHotNumber in", values, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberNotIn(List<Long> values) {
            addCriterion("SingerHotNumber not in", values, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberBetween(Long value1, Long value2) {
            addCriterion("SingerHotNumber between", value1, value2, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andSingerhotnumberNotBetween(Long value1, Long value2) {
            addCriterion("SingerHotNumber not between", value1, value2, "singerhotnumber");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("Alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("Alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("Alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("Alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("Alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("Alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("Alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("Alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("Alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("Alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("Alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("Alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("Alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("Alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeIsNull() {
            addCriterion("AlbumSize is null");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeIsNotNull() {
            addCriterion("AlbumSize is not null");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeEqualTo(Double value) {
            addCriterion("AlbumSize =", value, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeNotEqualTo(Double value) {
            addCriterion("AlbumSize <>", value, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeGreaterThan(Double value) {
            addCriterion("AlbumSize >", value, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeGreaterThanOrEqualTo(Double value) {
            addCriterion("AlbumSize >=", value, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeLessThan(Double value) {
            addCriterion("AlbumSize <", value, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeLessThanOrEqualTo(Double value) {
            addCriterion("AlbumSize <=", value, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeIn(List<Double> values) {
            addCriterion("AlbumSize in", values, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeNotIn(List<Double> values) {
            addCriterion("AlbumSize not in", values, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeBetween(Double value1, Double value2) {
            addCriterion("AlbumSize between", value1, value2, "albumsize");
            return (Criteria) this;
        }

        public Criteria andAlbumsizeNotBetween(Double value1, Double value2) {
            addCriterion("AlbumSize not between", value1, value2, "albumsize");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table singerbaseinfo
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}