package com.knight.Bean;

public class singerbaseinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.SingerId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long singerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.SingerName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String singername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.SingerImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String singerimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.SingerSex
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String singersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.SingerHotNumber
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long singerhotnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.Alias
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.AlbumSize
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Double albumsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column singerbaseinfo.BriefDesc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String briefdesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.SingerId
     *
     * @return the value of singerbaseinfo.SingerId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getSingerid() {
        return singerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.SingerId
     *
     * @param singerid the value for singerbaseinfo.SingerId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSingerid(Long singerid) {
        this.singerid = singerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.SingerName
     *
     * @return the value of singerbaseinfo.SingerName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSingername() {
        return singername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.SingerName
     *
     * @param singername the value for singerbaseinfo.SingerName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSingername(String singername) {
        this.singername = singername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.SingerImg
     *
     * @return the value of singerbaseinfo.SingerImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSingerimg() {
        return singerimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.SingerImg
     *
     * @param singerimg the value for singerbaseinfo.SingerImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSingerimg(String singerimg) {
        this.singerimg = singerimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.SingerSex
     *
     * @return the value of singerbaseinfo.SingerSex
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSingersex() {
        return singersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.SingerSex
     *
     * @param singersex the value for singerbaseinfo.SingerSex
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSingersex(String singersex) {
        this.singersex = singersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.SingerHotNumber
     *
     * @return the value of singerbaseinfo.SingerHotNumber
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getSingerhotnumber() {
        return singerhotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.SingerHotNumber
     *
     * @param singerhotnumber the value for singerbaseinfo.SingerHotNumber
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSingerhotnumber(Long singerhotnumber) {
        this.singerhotnumber = singerhotnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.Alias
     *
     * @return the value of singerbaseinfo.Alias
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.Alias
     *
     * @param alias the value for singerbaseinfo.Alias
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.AlbumSize
     *
     * @return the value of singerbaseinfo.AlbumSize
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Double getAlbumsize() {
        return albumsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.AlbumSize
     *
     * @param albumsize the value for singerbaseinfo.AlbumSize
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setAlbumsize(Double albumsize) {
        this.albumsize = albumsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column singerbaseinfo.BriefDesc
     *
     * @return the value of singerbaseinfo.BriefDesc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getBriefdesc() {
        return briefdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column singerbaseinfo.BriefDesc
     *
     * @param briefdesc the value for singerbaseinfo.BriefDesc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setBriefdesc(String briefdesc) {
        this.briefdesc = briefdesc;
    }
}