package com.knight.Bean;

public class songsheetinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheetinfo.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long musicid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheetinfo.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long sheetid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheetinfo.MusicId
     *
     * @return the value of songsheetinfo.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getMusicid() {
        return musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheetinfo.MusicId
     *
     * @param musicid the value for songsheetinfo.MusicId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setMusicid(Long musicid) {
        this.musicid = musicid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheetinfo.SheetId
     *
     * @return the value of songsheetinfo.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getSheetid() {
        return sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheetinfo.SheetId
     *
     * @param sheetid the value for songsheetinfo.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSheetid(Long sheetid) {
        this.sheetid = sheetid;
    }
}