package com.knight.Bean;

import java.util.Date;

public class songsheet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long sheetid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.SongSheetName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String songsheetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.Type
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.CoverImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String coverimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.Producer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String producer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.State
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.Time
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column songsheet.Introduce
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.SheetId
     *
     * @return the value of songsheet.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getSheetid() {
        return sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.SheetId
     *
     * @param sheetid the value for songsheet.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSheetid(Long sheetid) {
        this.sheetid = sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.SongSheetName
     *
     * @return the value of songsheet.SongSheetName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSongsheetname() {
        return songsheetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.SongSheetName
     *
     * @param songsheetname the value for songsheet.SongSheetName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSongsheetname(String songsheetname) {
        this.songsheetname = songsheetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.Type
     *
     * @return the value of songsheet.Type
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.Type
     *
     * @param type the value for songsheet.Type
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.CoverImg
     *
     * @return the value of songsheet.CoverImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getCoverimg() {
        return coverimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.CoverImg
     *
     * @param coverimg the value for songsheet.CoverImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setCoverimg(String coverimg) {
        this.coverimg = coverimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.Producer
     *
     * @return the value of songsheet.Producer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getProducer() {
        return producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.Producer
     *
     * @param producer the value for songsheet.Producer
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setProducer(String producer) {
        this.producer = producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.State
     *
     * @return the value of songsheet.State
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.State
     *
     * @param state the value for songsheet.State
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.Time
     *
     * @return the value of songsheet.Time
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.Time
     *
     * @param time the value for songsheet.Time
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column songsheet.Introduce
     *
     * @return the value of songsheet.Introduce
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column songsheet.Introduce
     *
     * @param introduce the value for songsheet.Introduce
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }
}