package com.knight.Bean;

import java.util.Date;

public class trackcomment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackcomment.trackId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long trackid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackcomment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackcomment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackcomment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long fabulous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackcomment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long commentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackcomment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long replycommentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trackcomment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackcomment.trackId
     *
     * @return the value of trackcomment.trackId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getTrackid() {
        return trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackcomment.trackId
     *
     * @param trackid the value for trackcomment.trackId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setTrackid(Long trackid) {
        this.trackid = trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackcomment.UserId
     *
     * @return the value of trackcomment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackcomment.UserId
     *
     * @param userid the value for trackcomment.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackcomment.date
     *
     * @return the value of trackcomment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackcomment.date
     *
     * @param date the value for trackcomment.date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackcomment.Fabulous
     *
     * @return the value of trackcomment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getFabulous() {
        return fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackcomment.Fabulous
     *
     * @param fabulous the value for trackcomment.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setFabulous(Long fabulous) {
        this.fabulous = fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackcomment.CommentId
     *
     * @return the value of trackcomment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackcomment.CommentId
     *
     * @param commentid the value for trackcomment.CommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setCommentid(Long commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackcomment.ReplyCommentId
     *
     * @return the value of trackcomment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getReplycommentid() {
        return replycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackcomment.ReplyCommentId
     *
     * @param replycommentid the value for trackcomment.ReplyCommentId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setReplycommentid(Long replycommentid) {
        this.replycommentid = replycommentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trackcomment.content
     *
     * @return the value of trackcomment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trackcomment.content
     *
     * @param content the value for trackcomment.content
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setContent(String content) {
        this.content = content;
    }
}