package com.knight.Bean;

import java.util.Date;

public class track {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.Date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.ImgContent1
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String imgcontent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.ImgContent2
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String imgcontent2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.ImgContent3
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String imgcontent3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.VideoContent
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String videocontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long fabulous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.TrackId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long trackid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column track.TextContent
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String textcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.UserId
     *
     * @return the value of track.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.UserId
     *
     * @param userid the value for track.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.Date
     *
     * @return the value of track.Date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.Date
     *
     * @param date the value for track.Date
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.ImgContent1
     *
     * @return the value of track.ImgContent1
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getImgcontent1() {
        return imgcontent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.ImgContent1
     *
     * @param imgcontent1 the value for track.ImgContent1
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setImgcontent1(String imgcontent1) {
        this.imgcontent1 = imgcontent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.ImgContent2
     *
     * @return the value of track.ImgContent2
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getImgcontent2() {
        return imgcontent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.ImgContent2
     *
     * @param imgcontent2 the value for track.ImgContent2
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setImgcontent2(String imgcontent2) {
        this.imgcontent2 = imgcontent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.ImgContent3
     *
     * @return the value of track.ImgContent3
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getImgcontent3() {
        return imgcontent3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.ImgContent3
     *
     * @param imgcontent3 the value for track.ImgContent3
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setImgcontent3(String imgcontent3) {
        this.imgcontent3 = imgcontent3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.VideoContent
     *
     * @return the value of track.VideoContent
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getVideocontent() {
        return videocontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.VideoContent
     *
     * @param videocontent the value for track.VideoContent
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setVideocontent(String videocontent) {
        this.videocontent = videocontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.Fabulous
     *
     * @return the value of track.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getFabulous() {
        return fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.Fabulous
     *
     * @param fabulous the value for track.Fabulous
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setFabulous(Long fabulous) {
        this.fabulous = fabulous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.TrackId
     *
     * @return the value of track.TrackId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getTrackid() {
        return trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.TrackId
     *
     * @param trackid the value for track.TrackId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setTrackid(Long trackid) {
        this.trackid = trackid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column track.TextContent
     *
     * @return the value of track.TextContent
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getTextcontent() {
        return textcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column track.TextContent
     *
     * @param textcontent the value for track.TextContent
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setTextcontent(String textcontent) {
        this.textcontent = textcontent;
    }
}