package com.knight.Bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class trackExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public trackExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUseridIsNull() {
            addCriterion("UserId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("UserId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("UserId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("UserId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("UserId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("UserId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("UserId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("UserId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("UserId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("UserId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("UserId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("UserId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("Date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("Date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("Date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("Date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("Date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("Date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("Date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("Date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("Date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("Date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("Date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("Date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andImgcontent1IsNull() {
            addCriterion("ImgContent1 is null");
            return (Criteria) this;
        }

        public Criteria andImgcontent1IsNotNull() {
            addCriterion("ImgContent1 is not null");
            return (Criteria) this;
        }

        public Criteria andImgcontent1EqualTo(String value) {
            addCriterion("ImgContent1 =", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1NotEqualTo(String value) {
            addCriterion("ImgContent1 <>", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1GreaterThan(String value) {
            addCriterion("ImgContent1 >", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1GreaterThanOrEqualTo(String value) {
            addCriterion("ImgContent1 >=", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1LessThan(String value) {
            addCriterion("ImgContent1 <", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1LessThanOrEqualTo(String value) {
            addCriterion("ImgContent1 <=", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1Like(String value) {
            addCriterion("ImgContent1 like", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1NotLike(String value) {
            addCriterion("ImgContent1 not like", value, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1In(List<String> values) {
            addCriterion("ImgContent1 in", values, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1NotIn(List<String> values) {
            addCriterion("ImgContent1 not in", values, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1Between(String value1, String value2) {
            addCriterion("ImgContent1 between", value1, value2, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent1NotBetween(String value1, String value2) {
            addCriterion("ImgContent1 not between", value1, value2, "imgcontent1");
            return (Criteria) this;
        }

        public Criteria andImgcontent2IsNull() {
            addCriterion("ImgContent2 is null");
            return (Criteria) this;
        }

        public Criteria andImgcontent2IsNotNull() {
            addCriterion("ImgContent2 is not null");
            return (Criteria) this;
        }

        public Criteria andImgcontent2EqualTo(String value) {
            addCriterion("ImgContent2 =", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2NotEqualTo(String value) {
            addCriterion("ImgContent2 <>", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2GreaterThan(String value) {
            addCriterion("ImgContent2 >", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2GreaterThanOrEqualTo(String value) {
            addCriterion("ImgContent2 >=", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2LessThan(String value) {
            addCriterion("ImgContent2 <", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2LessThanOrEqualTo(String value) {
            addCriterion("ImgContent2 <=", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2Like(String value) {
            addCriterion("ImgContent2 like", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2NotLike(String value) {
            addCriterion("ImgContent2 not like", value, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2In(List<String> values) {
            addCriterion("ImgContent2 in", values, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2NotIn(List<String> values) {
            addCriterion("ImgContent2 not in", values, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2Between(String value1, String value2) {
            addCriterion("ImgContent2 between", value1, value2, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent2NotBetween(String value1, String value2) {
            addCriterion("ImgContent2 not between", value1, value2, "imgcontent2");
            return (Criteria) this;
        }

        public Criteria andImgcontent3IsNull() {
            addCriterion("ImgContent3 is null");
            return (Criteria) this;
        }

        public Criteria andImgcontent3IsNotNull() {
            addCriterion("ImgContent3 is not null");
            return (Criteria) this;
        }

        public Criteria andImgcontent3EqualTo(String value) {
            addCriterion("ImgContent3 =", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3NotEqualTo(String value) {
            addCriterion("ImgContent3 <>", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3GreaterThan(String value) {
            addCriterion("ImgContent3 >", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3GreaterThanOrEqualTo(String value) {
            addCriterion("ImgContent3 >=", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3LessThan(String value) {
            addCriterion("ImgContent3 <", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3LessThanOrEqualTo(String value) {
            addCriterion("ImgContent3 <=", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3Like(String value) {
            addCriterion("ImgContent3 like", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3NotLike(String value) {
            addCriterion("ImgContent3 not like", value, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3In(List<String> values) {
            addCriterion("ImgContent3 in", values, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3NotIn(List<String> values) {
            addCriterion("ImgContent3 not in", values, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3Between(String value1, String value2) {
            addCriterion("ImgContent3 between", value1, value2, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andImgcontent3NotBetween(String value1, String value2) {
            addCriterion("ImgContent3 not between", value1, value2, "imgcontent3");
            return (Criteria) this;
        }

        public Criteria andVideocontentIsNull() {
            addCriterion("VideoContent is null");
            return (Criteria) this;
        }

        public Criteria andVideocontentIsNotNull() {
            addCriterion("VideoContent is not null");
            return (Criteria) this;
        }

        public Criteria andVideocontentEqualTo(String value) {
            addCriterion("VideoContent =", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentNotEqualTo(String value) {
            addCriterion("VideoContent <>", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentGreaterThan(String value) {
            addCriterion("VideoContent >", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentGreaterThanOrEqualTo(String value) {
            addCriterion("VideoContent >=", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentLessThan(String value) {
            addCriterion("VideoContent <", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentLessThanOrEqualTo(String value) {
            addCriterion("VideoContent <=", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentLike(String value) {
            addCriterion("VideoContent like", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentNotLike(String value) {
            addCriterion("VideoContent not like", value, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentIn(List<String> values) {
            addCriterion("VideoContent in", values, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentNotIn(List<String> values) {
            addCriterion("VideoContent not in", values, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentBetween(String value1, String value2) {
            addCriterion("VideoContent between", value1, value2, "videocontent");
            return (Criteria) this;
        }

        public Criteria andVideocontentNotBetween(String value1, String value2) {
            addCriterion("VideoContent not between", value1, value2, "videocontent");
            return (Criteria) this;
        }

        public Criteria andFabulousIsNull() {
            addCriterion("Fabulous is null");
            return (Criteria) this;
        }

        public Criteria andFabulousIsNotNull() {
            addCriterion("Fabulous is not null");
            return (Criteria) this;
        }

        public Criteria andFabulousEqualTo(Long value) {
            addCriterion("Fabulous =", value, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousNotEqualTo(Long value) {
            addCriterion("Fabulous <>", value, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousGreaterThan(Long value) {
            addCriterion("Fabulous >", value, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousGreaterThanOrEqualTo(Long value) {
            addCriterion("Fabulous >=", value, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousLessThan(Long value) {
            addCriterion("Fabulous <", value, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousLessThanOrEqualTo(Long value) {
            addCriterion("Fabulous <=", value, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousIn(List<Long> values) {
            addCriterion("Fabulous in", values, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousNotIn(List<Long> values) {
            addCriterion("Fabulous not in", values, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousBetween(Long value1, Long value2) {
            addCriterion("Fabulous between", value1, value2, "fabulous");
            return (Criteria) this;
        }

        public Criteria andFabulousNotBetween(Long value1, Long value2) {
            addCriterion("Fabulous not between", value1, value2, "fabulous");
            return (Criteria) this;
        }

        public Criteria andTrackidIsNull() {
            addCriterion("TrackId is null");
            return (Criteria) this;
        }

        public Criteria andTrackidIsNotNull() {
            addCriterion("TrackId is not null");
            return (Criteria) this;
        }

        public Criteria andTrackidEqualTo(Long value) {
            addCriterion("TrackId =", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotEqualTo(Long value) {
            addCriterion("TrackId <>", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidGreaterThan(Long value) {
            addCriterion("TrackId >", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidGreaterThanOrEqualTo(Long value) {
            addCriterion("TrackId >=", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidLessThan(Long value) {
            addCriterion("TrackId <", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidLessThanOrEqualTo(Long value) {
            addCriterion("TrackId <=", value, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidIn(List<Long> values) {
            addCriterion("TrackId in", values, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotIn(List<Long> values) {
            addCriterion("TrackId not in", values, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidBetween(Long value1, Long value2) {
            addCriterion("TrackId between", value1, value2, "trackid");
            return (Criteria) this;
        }

        public Criteria andTrackidNotBetween(Long value1, Long value2) {
            addCriterion("TrackId not between", value1, value2, "trackid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table track
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table track
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}