package com.knight.Bean;

public class usercollectioninfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercollectioninfo.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usercollectioninfo.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long sheetid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercollectioninfo.UserId
     *
     * @return the value of usercollectioninfo.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercollectioninfo.UserId
     *
     * @param userid the value for usercollectioninfo.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usercollectioninfo.SheetId
     *
     * @return the value of usercollectioninfo.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getSheetid() {
        return sheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usercollectioninfo.SheetId
     *
     * @param sheetid the value for usercollectioninfo.SheetId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSheetid(Long sheetid) {
        this.sheetid = sheetid;
    }
}