package com.knight.Bean;

import java.util.Date;

public class userbaseinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.UserName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.UserAccount
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String useraccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.UserPassword
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String userpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.UserHeadImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String userheadimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.Email
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.RegisterTime
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date registertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.Birthday
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.Location
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.Sex
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.MusicPreference
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String musicpreference;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.Status
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbaseinfo.Signature
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    private String signature;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.UserId
     *
     * @return the value of userbaseinfo.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.UserId
     *
     * @param userid the value for userbaseinfo.UserId
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.UserName
     *
     * @return the value of userbaseinfo.UserName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.UserName
     *
     * @param username the value for userbaseinfo.UserName
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.UserAccount
     *
     * @return the value of userbaseinfo.UserAccount
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.UserAccount
     *
     * @param useraccount the value for userbaseinfo.UserAccount
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.UserPassword
     *
     * @return the value of userbaseinfo.UserPassword
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.UserPassword
     *
     * @param userpassword the value for userbaseinfo.UserPassword
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.UserHeadImg
     *
     * @return the value of userbaseinfo.UserHeadImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getUserheadimg() {
        return userheadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.UserHeadImg
     *
     * @param userheadimg the value for userbaseinfo.UserHeadImg
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setUserheadimg(String userheadimg) {
        this.userheadimg = userheadimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.Email
     *
     * @return the value of userbaseinfo.Email
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.Email
     *
     * @param email the value for userbaseinfo.Email
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.RegisterTime
     *
     * @return the value of userbaseinfo.RegisterTime
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.RegisterTime
     *
     * @param registertime the value for userbaseinfo.RegisterTime
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.Birthday
     *
     * @return the value of userbaseinfo.Birthday
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.Birthday
     *
     * @param birthday the value for userbaseinfo.Birthday
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.Location
     *
     * @return the value of userbaseinfo.Location
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.Location
     *
     * @param location the value for userbaseinfo.Location
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.Sex
     *
     * @return the value of userbaseinfo.Sex
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.Sex
     *
     * @param sex the value for userbaseinfo.Sex
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.MusicPreference
     *
     * @return the value of userbaseinfo.MusicPreference
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getMusicpreference() {
        return musicpreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.MusicPreference
     *
     * @param musicpreference the value for userbaseinfo.MusicPreference
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setMusicpreference(String musicpreference) {
        this.musicpreference = musicpreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.Status
     *
     * @return the value of userbaseinfo.Status
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.Status
     *
     * @param status the value for userbaseinfo.Status
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbaseinfo.Signature
     *
     * @return the value of userbaseinfo.Signature
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbaseinfo.Signature
     *
     * @param signature the value for userbaseinfo.Signature
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }
}