package com.knight.Dao.Schedule;

import com.knight.Bean.accountConfig;
import com.knight.Bean.accountConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Repository
public interface accountConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    long countByExample(accountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int deleteByExample(accountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int insert(accountConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int insertSelective(accountConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    List<accountConfig> selectByExample(accountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") accountConfig record, @Param("example") accountConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int updateByExample(@Param("record") accountConfig record, @Param("example") accountConfigExample example);

    @Select(value = "select * from AccountConfig where status = 'true' or status = 'TRUE' LIMIT 1")
    accountConfig selectValidAccount();
}