package com.knight.Dao.Schedule;

import com.knight.Bean.ErrorInfo;
import com.knight.Bean.ErrorInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ErrorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    long countByExample(ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    int deleteByExample(ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    int insert(ErrorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    int insertSelective(ErrorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    List<ErrorInfo> selectByExampleWithBLOBs(ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    List<ErrorInfo> selectByExample(ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") ErrorInfo record, @Param("example") ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ErrorInfo record, @Param("example") ErrorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ErrorInfo
     *
     * @mbg.generated Sun Dec 29 09:19:54 CST 2019
     */
    int updateByExample(@Param("record") ErrorInfo record, @Param("example") ErrorInfoExample example);
}