package com.knight.Dao.Schedule;

import com.knight.Bean.scheduleTaskConfig;
import com.knight.Bean.scheduleTaskConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface scheduleTaskConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    long countByExample(scheduleTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int deleteByExample(scheduleTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int insert(scheduleTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int insertSelective(scheduleTaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    List<scheduleTaskConfig> selectByExampleWithBLOBs(scheduleTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    List<scheduleTaskConfig> selectByExample(scheduleTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") scheduleTaskConfig record, @Param("example") scheduleTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") scheduleTaskConfig record, @Param("example") scheduleTaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ScheduleTaskConfig
     *
     * @mbg.generated Sat Dec 28 16:54:50 CST 2019
     */
    int updateByExample(@Param("record") scheduleTaskConfig record, @Param("example") scheduleTaskConfigExample example);
}