spring:
  profiles:
    active: dev
  datasource:
    schedule:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: knightSql
      password: HelloKnight@2019
      url: jdbc:mysql://122.51.149.162:3306/ScheduleCollectionDB?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/knight/Mapper/*.xml
#  type-aliases-package: com.knight.Bean
logging:
  level:
    root: info
custom:
  ip: 127.0.0.1
  port: 3000
  CollectDaySongName: CollectSongTask

---
spring:
  datasource:
    musicsite:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: knightSql
      password: HelloKnight@2019
      url: jdbc:mysql://122.51.149.162:3306/musicsite?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
  profiles: prod
---
spring:
  datasource:
    musicsite:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/musicsite?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
  profiles: dev

