package com.knight.Dao.MusicSite;

import com.knight.Bean.lrc;
import com.knight.Bean.lrcExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface lrcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    long countByExample(lrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int deleteByExample(lrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insert(lrc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insertSelective(lrc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<lrc> selectByExampleWithBLOBs(lrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<lrc> selectByExample(lrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") lrc record, @Param("example") lrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") lrc record, @Param("example") lrcExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lrc
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") lrc record, @Param("example") lrcExample example);
}