package com.knight.Dao.MusicSite;

import com.knight.Bean.relationship;
import com.knight.Bean.relationshipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface relationshipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    long countByExample(relationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int deleteByExample(relationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int deleteByPrimaryKey(String nativemusicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int insert(relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int insertSelective(relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    List<relationship> selectByExample(relationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    relationship selectByPrimaryKey(String nativemusicid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") relationship record, @Param("example") relationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int updateByExample(@Param("record") relationship record, @Param("example") relationshipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int updateByPrimaryKeySelective(relationship record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relationshipinfo
     *
     * @mbg.generated Fri Jan 03 13:42:08 CST 2020
     */
    int updateByPrimaryKey(relationship record);
}