package com.knight.Dao.MusicSite;

import com.knight.Bean.sheetcomment;
import com.knight.Bean.sheetcommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface sheetcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    long countByExample(sheetcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int deleteByExample(sheetcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insert(sheetcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insertSelective(sheetcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<sheetcomment> selectByExampleWithBLOBs(sheetcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<sheetcomment> selectByExample(sheetcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") sheetcomment record, @Param("example") sheetcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") sheetcomment record, @Param("example") sheetcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sheetcomment
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") sheetcomment record, @Param("example") sheetcommentExample example);
}