package com.knight.Dao.MusicSite;

import com.knight.Bean.singerbaseinfo;
import com.knight.Bean.singerbaseinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface singerbaseinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    long countByExample(singerbaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int deleteByExample(singerbaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insert(singerbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insertSelective(singerbaseinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<singerbaseinfo> selectByExampleWithBLOBs(singerbaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<singerbaseinfo> selectByExample(singerbaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") singerbaseinfo record, @Param("example") singerbaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") singerbaseinfo record, @Param("example") singerbaseinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table singerbaseinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") singerbaseinfo record, @Param("example") singerbaseinfoExample example);
}