package com.knight.Dao.MusicSite;

import com.knight.Bean.songsheetinfo;
import com.knight.Bean.songsheetinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface songsheetinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheetinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    long countByExample(songsheetinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheetinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int deleteByExample(songsheetinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheetinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insert(songsheetinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheetinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insertSelective(songsheetinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheetinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<songsheetinfo> selectByExample(songsheetinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheetinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") songsheetinfo record, @Param("example") songsheetinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table songsheetinfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") songsheetinfo record, @Param("example") songsheetinfoExample example);
}