package com.knight.Dao.MusicSite;

import com.knight.Bean.userauthority;
import com.knight.Bean.userauthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface userauthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    long countByExample(userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int deleteByExample(userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insert(userauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insertSelective(userauthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<userauthority> selectByExample(userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") userauthority record, @Param("example") userauthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userauthority
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") userauthority record, @Param("example") userauthorityExample example);
}