package com.knight.Dao.MusicSite;

import com.knight.Bean.usercollectioninfo;
import com.knight.Bean.usercollectioninfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface usercollectioninfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    long countByExample(usercollectioninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int deleteByExample(usercollectioninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insert(usercollectioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int insertSelective(usercollectioninfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    List<usercollectioninfo> selectByExample(usercollectioninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExampleSelective(@Param("record") usercollectioninfo record, @Param("example") usercollectioninfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usercollectioninfo
     *
     * @mbg.generated Sat Dec 28 16:52:58 CST 2019
     */
    int updateByExample(@Param("record") usercollectioninfo record, @Param("example") usercollectioninfoExample example);
}